### ISSUE TITLE
Modpack won't start after selecting a resourcepack

### ISSUE THREAD

**Issue by PrinceEvile** [gilfort/CurseOfGaia#2]
[crash-2016-10-20_13.28.04-client.txt](https://github.com/gilfort/CurseOfGaia/files/541557/crash-2016-10-20_13.28.04-client.txt)

Modpack won't start after selecting a resourcepack. Not sure if that's the matter though.
I've attached the crash-report.
Hopefully it can be fixed soon ^^

Resourcepack: Sphax pureBDcraft. Also Tried out the (incompatible version) sound-pack, but deleted it as it wouldn't start.
RAM: 4096MB RAM (in curse and in MC-launcher -> -Xmx4096M)

**Comment by gilfort** [comment]
OutOfMemory error, try adding more Ram or using a less detailed Texturepack
