### ISSUE TITLE
" issues with Crafting

### ISSUE THREAD

**Issue by OGTEnzoHD** [gilfort/CurseOfGaia#3]
1st issue, to make potash you have to use the stoked cauldron, i have made the stoked cauldron and set it up correctly, however it wont make any recipies.

2nd issue to make the blood alter, you need a sacrificial knife, which requires a blank slate which requires the blood alter.

**Comment by gilfort** [comment]
Nothing wrong here 
you need a hibachi to fire a cauldron and the dagger is hidden but available
