### ISSUE TITLE
[Comment] Just a couple of observations. 

### ISSUE THREAD

**Issue by llloyd4** [gilfort/CurseOfGaia#8]
So feel free to round file it if ya want. >.< So, good concept, cursed earth, but not the barren wasteland like Regrowth or Crash Landing. But I only have two *minor* complaints. Well, three come to think about it. I have it set to Easy and I am getting a bunch of mobs spawning with armor. I did copy over my Mekanism config from another mod pack, the version numbers are the same so it's compatible, and it added a bunch of config options. Two, even on Easy the mobs are zipping about like they're on Jet and Three the skeletons fire their bows very rapidly. One sec I am like "Oh hell, a skeleton wearing armor, that's just rude." the next I am a pin cushion. >.< It a very rough start given I keep getting owned by invisible creepers (Like, seriously, one second they're flying at me like they're on speed, the next they vanish and then BOOM!) or machine gun bow wielding armor wearing skeletons that refuse to burn like mobs are suppose to at sun up. >.< But beyond that, I like the mod pack, good set of mods, interesting concept, I like the GUI at the top left, etc.

**Comment by gilfort** [comment]
I'll take a look back into Rough mobs - thats the mod making mobs this strong. Its intentional that they're very strong, but i'm pretty sure i disabled invisible creepers!
Thanks for the comment!

**Comment by gilfort** [comment]
Should be fixed with the newest version.
